"""replace transaction type enum with boolean

Revision ID: 57485db477a9
Revises: 5b11ab5b70bb
Create Date: 2023-04-10 15:27:23.015803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57485db477a9'
down_revision = '5b11ab5b70bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_debit', sa.Boolean(), nullable=False))
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', postgresql.ENUM('CREDIT', 'DEBIT', name='transaction_type'), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'is_debit')
    # ### end Alembic commands ###
